Algoritmo "impostoDeRenda"

Var
   impostoDeRenda : real

Inicio
   escreval ("Escreva qual foi seu redimento tributável")
   leia (impostoDeRenda)
   
   se impostoDeRenda > 28559.70 entao
      escreval ("Seu rendimento foi superior a R$28.559,00")
      escreval ("Você tera que pagar Imposto de Renda")
   senao
      escreval ("Voce não tera que pagar o Imposto de Renda")
   fimse

Fimalgoritmo